-- =============================================================================
-- Migration: 20261006000003_payment_functions.sql
-- Description: Hardened atomic financial functions for manual payments, voiding, and public verification
-- Pre-Production Pilot System
-- =============================================================================

-- 1. ATOMIC MANUAL PAYMENT FUNCTION (SECURITY DEFINER WITH SEARCH_PATH ISOLATION)
CREATE OR REPLACE FUNCTION public.record_manual_payment_atomic(
    p_student_id UUID,
    p_semester_id UUID,
    p_amount NUMERIC(12, 2),
    p_payment_method public.payment_method,
    p_payment_date DATE,
    p_payment_time TIME,
    p_reference_number VARCHAR(100),
    p_notes TEXT,
    p_admin_id UUID,
    p_idempotency_key VARCHAR(100),
    p_verification_hash VARCHAR(64) -- Pre-computed by trusted server-side Node.js runtime
)
RETURNS TABLE (
    transaction_id UUID,
    receipt_id UUID,
    transaction_number VARCHAR(50),
    receipt_number VARCHAR(50)
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_due_id UUID;
    v_remaining NUMERIC(12, 2);
    v_net_due NUMERIC(12, 2);
    v_txn_seq BIGINT;
    v_rcp_seq BIGINT;
    v_txn_num VARCHAR(50);
    v_rcp_num VARCHAR(50);
    v_txn_id UUID;
    v_rcp_id UUID;
    v_year_str VARCHAR(4);
    v_caller_role public.user_role;
BEGIN
    -- 1.1 Authentication & Caller Spoofing Defense:
    -- If executed from a client context with auth.uid(), caller MUST match p_admin_id
    IF auth.uid() IS NOT NULL AND auth.uid() != p_admin_id THEN
        RAISE EXCEPTION 'UNAUTHORIZED: Authenticated caller (%) does not match specified admin_id (%)', auth.uid(), p_admin_id;
    END IF;

    -- 1.2 Verify caller is an active authorized admin in database
    SELECT p.role INTO v_caller_role
    FROM public.admins a
    JOIN public.profiles p ON p.id = a.id
    WHERE a.id = p_admin_id AND p.is_active = TRUE;

    IF v_caller_role IS NULL OR v_caller_role NOT IN ('ADMIN', 'SUPER_ADMIN') THEN
        RAISE EXCEPTION 'FORBIDDEN: Caller (%) is not an active authorized administrator', p_admin_id;
    END IF;

    -- 1.3 Validate Verification Hash Format (Must be 64-character lowercase/uppercase hex string)
    IF p_verification_hash IS NULL OR LENGTH(p_verification_hash) != 64 OR p_verification_hash !~ '^[a-fA-F0-9]{64}$' THEN
        RAISE EXCEPTION 'INVALID_HASH: Verification hash must be a valid 64-character hex string generated by the server';
    END IF;

    -- 1.4 Validate Payment Amount is positive
    IF p_amount <= 0 THEN
        RAISE EXCEPTION 'INVALID_AMOUNT: Payment amount must be strictly greater than 0';
    END IF;

    -- 1.5 Idempotency Check
    IF EXISTS (SELECT 1 FROM public.transactions WHERE idempotency_key = p_idempotency_key) THEN
        RAISE EXCEPTION 'DUPLICATE_SUBMISSION: A transaction with idempotency key (%) already exists', p_idempotency_key;
    END IF;

    -- 1.6 Concurrency Lock: Lock student_due row FOR UPDATE to prevent race conditions
    SELECT id, remaining_balance, net_due_amount INTO v_due_id, v_remaining, v_net_due
    FROM public.student_dues
    WHERE student_id = p_student_id AND semester_id = p_semester_id
    FOR UPDATE;

    IF v_due_id IS NULL THEN
        RAISE EXCEPTION 'DUE_NOT_FOUND: No fee record found for student (%) in semester (%)', p_student_id, p_semester_id;
    END IF;

    -- 1.7 Overpayment Protection
    IF p_amount > v_remaining THEN
        RAISE EXCEPTION 'OVERPAYMENT: Payment amount (EGP %) exceeds outstanding balance (EGP %)', p_amount, v_remaining;
    END IF;

    -- 1.8 Generate Monotonic Sequence Numbers
    v_year_str := TO_CHAR(NOW(), 'YYYY');
    v_txn_seq := nextval('txn_number_seq');
    v_rcp_seq := nextval('rcp_number_seq');
    v_txn_num := 'CUFE-TXN-' || v_year_str || '-' || LPAD(v_txn_seq::text, 6, '0');
    v_rcp_num := 'CUFE-RCP-' || v_year_str || '-' || LPAD(v_rcp_seq::text, 6, '0');

    -- 1.9 Insert Transaction (status: COMPLETED)
    INSERT INTO public.transactions (
        transaction_number, student_id, semester_id, student_due_id,
        amount, currency, payment_method, payment_date, payment_time,
        reference_number, notes, status, idempotency_key, recorded_by
    ) VALUES (
        v_txn_num, p_student_id, p_semester_id, v_due_id,
        p_amount, 'EGP', p_payment_method, p_payment_date, p_payment_time,
        p_reference_number, p_notes, 'COMPLETED', p_idempotency_key, p_admin_id
    ) RETURNING id INTO v_txn_id;

    -- 1.10 Update Student Due (Atomically increments paid_amount and recomputes status)
    UPDATE public.student_dues
    SET 
        paid_amount = paid_amount + p_amount,
        status = CASE 
            WHEN (paid_amount + p_amount) >= (original_amount - discount_amount) THEN 'PAID'::public.due_status
            ELSE 'PARTIALLY_PAID'::public.due_status
        END,
        updated_at = NOW()
    WHERE id = v_due_id;

    -- 1.11 Insert Receipt (Stores metadata snapshot + pre-computed server SHA-256 hash)
    INSERT INTO public.receipts (
        receipt_number, transaction_id, student_id,
        total_amount, currency, verification_hash, metadata
    ) VALUES (
        v_rcp_num, v_txn_id, p_student_id,
        p_amount, 'EGP', p_verification_hash,
        jsonb_build_object(
            'recorded_by', p_admin_id,
            'payment_method', p_payment_method,
            'payment_date', p_payment_date,
            'reference_number', p_reference_number,
            'txn_number', v_txn_num
        )
    ) RETURNING id INTO v_rcp_id;

    -- 1.12 Append-Only Audit Log
    INSERT INTO public.audit_logs (
        actor_id, actor_role, action, entity_name, entity_id, before_state, after_state
    ) VALUES (
        p_admin_id, v_caller_role, 'PAYMENT_RECORDED', 'transactions', v_txn_id::text,
        jsonb_build_object('previous_balance', v_remaining),
        jsonb_build_object(
            'amount', p_amount,
            'new_balance', (v_remaining - p_amount),
            'txn_number', v_txn_num,
            'rcp_number', v_rcp_num,
            'student_id', p_student_id
        )
    );

    RETURN QUERY SELECT v_txn_id, v_rcp_id, v_txn_num, v_rcp_num;
END;
$$;

-- 2. CONTROLLED VOID TRANSACTION FUNCTION (SECURITY DEFINER WITH SEARCH_PATH ISOLATION)
CREATE OR REPLACE FUNCTION public.void_transaction_atomic(
    p_transaction_id UUID,
    p_void_reason TEXT,
    p_admin_id UUID
)
RETURNS TABLE (
    transaction_id UUID,
    restored_balance NUMERIC(12, 2)
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_txn RECORD;
    v_due RECORD;
    v_can_void BOOLEAN;
    v_new_balance NUMERIC(12, 2);
    v_caller_role public.user_role;
BEGIN
    -- 2.1 Authentication & Caller Spoofing Defense
    IF auth.uid() IS NOT NULL AND auth.uid() != p_admin_id THEN
        RAISE EXCEPTION 'UNAUTHORIZED: Authenticated caller (%) does not match specified admin_id (%)', auth.uid(), p_admin_id;
    END IF;

    -- 2.2 Verify caller has void permissions
    SELECT a.can_void_payments, p.role INTO v_can_void, v_caller_role
    FROM public.admins a
    JOIN public.profiles p ON p.id = a.id
    WHERE a.id = p_admin_id AND p.is_active = TRUE;

    IF v_can_void IS NOT TRUE THEN
        RAISE EXCEPTION 'FORBIDDEN: Administrator (%) does not possess void permissions', p_admin_id;
    END IF;

    -- 2.3 Validate reason length
    IF LENGTH(TRIM(p_void_reason)) < 10 THEN
        RAISE EXCEPTION 'INVALID_REASON: A detailed void reason of at least 10 characters is required';
    END IF;

    -- 2.4 Fetch and lock transaction
    SELECT * INTO v_txn
    FROM public.transactions
    WHERE id = p_transaction_id
    FOR UPDATE;

    IF v_txn.id IS NULL THEN
        RAISE EXCEPTION 'TRANSACTION_NOT_FOUND: Transaction (%) does not exist', p_transaction_id;
    END IF;

    IF v_txn.status = 'VOIDED' THEN
        RAISE EXCEPTION 'ALREADY_VOIDED: Transaction (%) is already voided', p_transaction_id;
    END IF;

    -- 2.5 Lock student due row
    SELECT * INTO v_due
    FROM public.student_dues
    WHERE id = v_txn.student_due_id
    FOR UPDATE;

    -- 2.6 Reverse paid amount on due
    UPDATE public.student_dues
    SET 
        paid_amount = GREATEST(0, paid_amount - v_txn.amount),
        status = CASE 
            WHEN (paid_amount - v_txn.amount) <= 0 THEN 'UNPAID'::public.due_status
            ELSE 'PARTIALLY_PAID'::public.due_status
        END,
        updated_at = NOW()
    WHERE id = v_txn.student_due_id
    RETURNING remaining_balance INTO v_new_balance;

    -- 2.7 Update transaction status to VOIDED
    UPDATE public.transactions
    SET 
        status = 'VOIDED',
        void_reason = p_void_reason,
        voided_at = NOW(),
        voided_by = p_admin_id,
        updated_at = NOW()
    WHERE id = p_transaction_id;

    -- 2.8 Record in Audit Log
    INSERT INTO public.audit_logs (
        actor_id, actor_role, action, entity_name, entity_id, before_state, after_state
    ) VALUES (
        p_admin_id, v_caller_role, 'PAYMENT_VOIDED', 'transactions', p_transaction_id::text,
        jsonb_build_object('status', 'COMPLETED', 'amount', v_txn.amount),
        jsonb_build_object('status', 'VOIDED', 'void_reason', p_void_reason, 'restored_balance', v_new_balance)
    );

    RETURN QUERY SELECT p_transaction_id, v_new_balance;
END;
$$;

-- 3. PUBLIC PRIVACY-PRESERVING RECEIPT VERIFICATION FUNCTION (STABLE SECURITY DEFINER)
-- EXPOSES ONLY 8 SAFE NON-PII FIELDS (Zero Student Name, ID, National ID, Phone, or Email)
CREATE OR REPLACE FUNCTION public.verify_receipt_public(
    p_verification_hash VARCHAR(64)
)
RETURNS TABLE (
    is_valid BOOLEAN,
    receipt_number VARCHAR(50),
    transaction_number VARCHAR(50),
    amount NUMERIC(12, 2),
    currency VARCHAR(3),
    payment_date DATE,
    payment_status public.transaction_status,
    issued_at TIMESTAMPTZ
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        TRUE AS is_valid,
        r.receipt_number,
        t.transaction_number,
        r.total_amount,
        r.currency,
        t.payment_date,
        t.status,
        r.issued_at
    FROM public.receipts r
    JOIN public.transactions t ON t.id = r.transaction_id
    WHERE r.verification_hash = p_verification_hash;
END;
$$;

-- =============================================================================
-- 4. RPC EXECUTION PRIVILEGE HARDENING
-- =============================================================================

-- Revoke default public/anon execute on sensitive financial RPCs
REVOKE EXECUTE ON FUNCTION public.record_manual_payment_atomic FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.record_manual_payment_atomic FROM anon;
REVOKE EXECUTE ON FUNCTION public.void_transaction_atomic FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.void_transaction_atomic FROM anon;

-- Grant EXECUTE to authenticated users and service_role
-- (Internal auth.uid() check ensures students cannot execute as admins)
GRANT EXECUTE ON FUNCTION public.record_manual_payment_atomic TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.void_transaction_atomic TO authenticated, service_role;

-- Public verification function is intentionally accessible to everyone (QR scanner)
REVOKE EXECUTE ON FUNCTION public.verify_receipt_public FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.verify_receipt_public TO anon, authenticated, service_role;
